# Generated by Django 3.1.3 on 2020-11-19 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_auto_20201119_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
